org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.93
neo_version_range=[26.1.2.93,)
loader_version_range=[4,)
jei_version=29.21.0.66

mod_id=jei_structures
mod_name=JEI Structures
mod_license=All Rights Reserved
mod_version=1.9
mod_group_id=org.hp
mod_authors=HP
mod_description=为结构、生物与战利品提供一次导出后可反查的JEI结构索引附属。
